''' jenkins post build script to parse output.xml generated by the
 robot test suite '''

import sys
import os
import time
import datetime

from xml.etree import ElementTree as ET
from xml.etree.ElementTree import Element
from xml.etree.ElementTree import ElementTree

robotoutputfile = "output.xml"
parsedfile = "parsedoutput.xml"
count = 0

while True:
        if(os.path.isfile(robotoutputfile)):
            tree = ET.parse(robotoutputfile)
            newroot = Element('test')
            newtree = ElementTree(newroot)
            for elem in tree.iter(tag='test'):
                current_element = Element('testname')
                current_element.text = elem.attrib['name']
                status_elem = elem.find('status')
                start = datetime.datetime.strptime(status_elem.
                                                   attrib['starttime'],
                                                   '%Y%m%d %H:%M:%S.%f')
                end = datetime.datetime.strptime(status_elem.
                                                 attrib['endtime'],
                                                 '%Y%m%d %H:%M:%S.%f')
                difference = end - start
                current_element.set('executiontime', str(difference))
                newroot.append(current_element)
                newtree.write(open(parsedfile, 'w'))
            print ("Succesfully generated the " + parsedfile)
            break
        count = count + 1
        if count == 5:
            print ("coundn't find the file " + filename + " quiting after " +
                   str(count) + " attempts")
            break
        else:
            time.sleep(180)
            continue
