'''
Python Script which parses the output.xml generated by the robot test suite 
to generate a more meaningful output file parsedoutput.xml which includes 
the operation  and execution time for plotting the time graphs on jenkins 
using xpath across builds
'''

from xml.etree.ElementTree import ElementTree
from xml.etree.ElementTree import Element
import xml.etree.ElementTree as ET
import datetime
import os

fname = "output.xml"

while True:
 if os.path.isfile(fname):

   tree = ET.parse(fname)
   root = tree.getroot()

   newroot=Element('test')
   newtree=ElementTree(newroot)

   for elem in tree.iter(tag='test'):
    current_element = Element('testname' )
    current_element.text=elem.attrib['name']
    status_elem = elem.find('status')
    start = datetime.datetime.strptime(status_elem.attrib['starttime'],'%Y%m%d %H:%M:%S.%f')
    end   = datetime.datetime.strptime(status_elem.attrib['endtime'],'%Y%m%d %H:%M:%S.%f')
    diff = end - start 
    difference = str(diff)
    current_element.set('executiontime', difference)
    newroot.append(current_element)
 
   newtree.write(open('parsedoutput.xml','w'))
   break
 else:
  print "no such file " + fname + " exists waiting for the file"
  continue

