# ODL Releng build templates
- project:
    name: PROJECT_SHORTNAME
    jobs:
        - '{name}-clm-{stream}'
        - '{name}-distribution-{stream}'
        - '{name}-distribution-check-{stream}'
        - '{name}-integration-{stream}'
        - '{name}-merge-{stream}'
        - '{name}-periodic-{stream}'
        - '{name}-sonar'
        - '{name}-validate-autorelease-{stream}'
        - '{name}-verify-{stream}'

    # stream:    release stream (eg. stable-lithium or beryllium)
    # branch:    git branch (eg. stable/lithium or master)
    STREAMS
    project: 'PROJECT_PATH'
    mvn-settings: 'JENKINS_SETTINGS'
    mvn-goals: 'MAVEN_GOALS'
    mvn-opts: 'MAVEN_OPTS'
    dependencies: 'DEPENDENCIES'
    email-upstream: 'EMAIL_PREFIX'
    archive-artifacts: 'ARCHIVE_ARTIFACTS'
