# REMOVE THIS LINE IF YOU WANT TO CUSTOMIZE ANYTHING BELOW
# Otherwise this file will be automatically overwritten by the template
# autobuilder.

# ODL Releng build templates
- project:
    name: PROJECT
    jobs:
JOB_TEMPLATES

    # stream:    release stream (eg. stable-lithium or beryllium)
    # branch:    git branch (eg. stable/lithium or master)
    STREAMS
    project: 'PROJECT'

# For the Job templates below replace instances of:
# PROJECT with your project name (eg. controller)
# MAVEN_GOALS with your maven goals to build
# MAVEN_OPTS with your maven options to build
