---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  vars:
    openvswitch_version: 2.8.2
    openvswitch_checksum: sha256:87b4a7e7134a44ce1f808d3415a2244b4518c2b0b2a42fa2f8231e592f13103d
    k8s_version: 1.9.4
    openvswitch_package_cache: /vagrant/cache/ovs
    golang_package_cache: /vagrant/cache/golang
    golang_version: 1.11.4
    golang_checksum: sha256:fb26c30e6a04ad937bbc657a1b5bba92f80096af1e8ee6da6430c045a8db3a5b

  pre_tasks:
    - include_role: name=lfit.system-update

  roles:
    - lfit.docker-install
    - fkautz.bridge-utils-install
    - fkautz.golang-install
    - fkautz.kubernetes-install
    - fkautz.openvswitch-install

- hosts: all
  tasks:
    - name: Make example directory
      file:
        path: /opt/k8s-examples
        state: directory
      become: true
    - name: Copy example files to example directory
      synchronize:
        src: ../provision/examples/
        dest: /opt/k8s-examples/
      become: true

  post_tasks:
    - name: System Reseal
      script: ../common-packer/provision/system-reseal.sh
      become: true
