---
- import_playbook: ../common-packer/provision/baseline.yaml
- import_playbook: ../common-packer/provision/docker.yaml

- hosts: all
  become_user: root
  become_method: sudo
  vars:
    elastic_search_checksum: sha256:0aa58947d66b487488e86059352deb7c6cab5da4accdff043cce9fed7c3d2fa7
    elastic_search_version: 1.7.5

  pre_tasks:
    - include_role: name=lfit.system-update

  tasks:
    - name: Install Elastic Search
      block:
        - name: "Fetch Elastic Search to /tmp/elasticsearch-{{elastic_search_version}}.tar.gz"
          get_url:
            url: "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{elastic_search_version}}.tar.gz"
            dest: "/tmp/elasticsearch-{{elastic_search_version}}.tar.gz"
            checksum: "{{elastic_search_checksum}}"
        - name: Make /tmp/elasticsearch directory
          file:
            path: /tmp/elasticsearch
            state: directory
            mode: 0755
        - name: Untar Elastic Search to /tmp/elasticsearch
          unarchive:
            src: "/tmp/elasticsearch-{{elastic_search_version}}.tar.gz"
            dest: /tmp/elasticsearch
            remote_src: true

  post_tasks:
    - name: System Reseal
      script: ../common-packer/provision/system-reseal.sh
      become: true
