---
#- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo
  vars:
    cassandra_checksum: sha256:a95ba4e2c9345b31310d14507e8889797cc626bc793fd341fff8ff8cba3131cd
    cassandra_version: 2.1.16
    elastic_search_checksum: sha256:0aa58947d66b487488e86059352deb7c6cab5da4accdff043cce9fed7c3d2fa7
    elastic_search_version: 1.7.5
    hbase_checksum: sha256:9cd990939403fd43dfb665b14603e3772ca3ed813a6e21a81de1778583b35eb8
    hbase_version: 0.94.27
    openjdk10_checksum: 'sha256:f3b26abc9990a0b8929781310e14a339a7542adfd6596afb842fa0dd7e3848b2'
    openjdk10_url: https://download.java.net/java/GA/jdk10/{{openjdk10_version}}/19aef61b38124481863b1413dce1855f/13/openjdk-{{openjdk10_version}}_linux-x64_bin.tar.gz
    openjdk10_version: 10.0.2
    openjdk11_checksum: 'sha256:3784cfc4670f0d4c5482604c7c513beb1a92b005f569df9bf100e8bef6610f2e'
    openjdk11_url: https://download.java.net/java/ga/jdk11/openjdk-{{openjdk11_version}}_linux-x64_bin.tar.gz
    openjdk11_version: 11

  pre_tasks:
    - name: 'Fail build'
      yum:
        name: git
        state: present

  roles:
    - lfit.mono-install

  tasks:
    - name: 'Install OpenJDK {{openjdk10_version}}'
      block:
        - name: 'Fetch OpenJDK {{openjdk10_version}} to /tmp/jdk-{{openjdk10_version}}_linux-x64_bin.tar.gz'
          get_url:
            url: "{{openjdk10_url}}"
            dest: '/tmp/jdk-{{openjdk10_version}}_linux-x64_bin.tar.gz'
            checksum: '{{openjdk10_checksum}}'
        - name: 'Untar OpenJDK {{openjdk10_version}} in /opt/'
          unarchive:
            src: '/tmp/jdk-{{openjdk10_version}}_linux-x64_bin.tar.gz'
            dest: /opt/
            mode: 0755
            remote_src: true
          become: true
        - name: 'Setup Java master and slave links for OpenJDK {{openjdk10_version}}'
          command: 'alternatives --install "/usr/bin/java" "java" "/opt/jdk-{{openjdk10_version}}/bin/java" 10 \
                    --slave "/usr/bin/jar" "jar" "/opt/jdk-{{openjdk10_version}}/bin/jar" \
                    --slave "/usr/bin/jarsigner" "jarsigner" "/opt/jdk-{{openjdk10_version}}/bin/jarsigner" \
                    --slave "/usr/bin/javac" "javac" "/opt/jdk-{{openjdk10_version}}/bin/javac" \
                    --slave "/usr/bin/javadoc" "javadoc" "/opt/jdk-{{openjdk10_version}}/bin/javadoc" \
                    --slave "/usr/bin/javah" "javah" "/opt/jdk-{{openjdk10_version}}/bin/javah" \
                    --slave "/usr/bin/javap" "javap" "/opt/jdk-{{openjdk10_version}}/bin/javap" \
                    --slave "/usr/bin/javaws" "javaws" "/opt/jdk-{{openjdk10_version}}/bin/javaws"'
          become: true
    - name: 'Install OpenJDK {{openjdk11_version}}'
      block:
        - name: 'Fetch OpenJDK 11 to /tmp/jdk-{{openjdk11_version}}_linux-x64_bin.tar.gz'
          get_url:
            url: "{{openjdk11_url}}"
            dest: '/tmp/jdk-{{openjdk11_version}}_linux-x64_bin.tar.gz'
            checksum: '{{openjdk11_checksum}}'
        - name: 'Untar OpenJDK {{openjdk11_version}} in /opt/'
          unarchive:
            src: '/tmp/jdk-{{openjdk11_version}}_linux-x64_bin.tar.gz'
            dest: /opt/
            mode: 0755
            remote_src: true
          become: true
        - name: 'Setup Java master and slave links for OpenJDK {{openjdk11_version}}'
          command: 'alternatives --install "/usr/bin/java" "java" "/opt/jdk-{{openjdk11_version}}/bin/java" 10 \
                    --slave "/usr/bin/jar" "jar" "/opt/jdk-{{openjdk11_version}}/bin/jar" \
                    --slave "/usr/bin/jarsigner" "jarsigner" "/opt/jdk-{{openjdk11_version}}/bin/jarsigner" \
                    --slave "/usr/bin/javac" "javac" "/opt/jdk-{{openjdk11_version}}/bin/javac" \
                    --slave "/usr/bin/javadoc" "javadoc" "/opt/jdk-{{openjdk11_version}}/bin/javadoc" \
                    --slave "/usr/bin/javah" "javah" "/opt/jdk-{{openjdk11_version}}/bin/javah" \
                    --slave "/usr/bin/javap" "javap" "/opt/jdk-{{openjdk11_version}}/bin/javap" \
                    --slave "/usr/bin/javaws" "javaws" "/opt/jdk-{{openjdk11_version}}/bin/javaws"'
          become: true
    - name: Install Cassandra Server
      block:
        - name: 'Fetch Cassandra Server to /tmp/apache-cassandra-{{cassandra_version}}-bin.tar.gz'
          get_url:
            url: 'https://archive.apache.org/dist/cassandra/{{cassandra_version}}/apache-cassandra-{{cassandra_version}}-bin.tar.gz'
            dest: '/tmp/apache-cassandra-{{cassandra_version}}-bin.tar.gz'
            checksum: '{{cassandra_checksum}}'
        - name: Make /tmp/cassandra directory
          file:
            path: /tmp/cassandra
            state: directory
            mode: 0755
        - name: Untar Cassandra server to /tmp/cassandra
          unarchive:
            src: '/tmp/apache-cassandra-{{cassandra_version}}-bin.tar.gz'
            dest: /tmp/cassandra
            remote_src: true
    - name: Install Elastic Search
      block:
        - name: 'Fetch Elastic Search to /tmp/elasticsearch-{{elastic_search_version}}.tar.gz'
          get_url:
            url: 'https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{elastic_search_version}}.tar.gz'
            dest: '/tmp/elasticsearch-{{elastic_search_version}}.tar.gz'
            checksum: '{{elastic_search_checksum}}'
        - name: Make /tmp/elasticsearch directory
          file:
            path: /tmp/elasticsearch
            state: directory
            mode: 0755
        - name: Untar Elastic Search to /tmp/elasticsearch
          unarchive:
            src: '/tmp/elasticsearch-{{elastic_search_version}}.tar.gz'
            dest: /tmp/elasticsearch
            remote_src: true
    - name: Install HBase Server
      block:
        - name: 'Fetch HBase to /tmp/hbase-{{hbase_version}}.tar.gz'
          get_url:
            url: 'https://archive.apache.org/dist/hbase/hbase-{{hbase_version}}/hbase-{{hbase_version}}.tar.gz'
            dest: '/tmp/hbase-{{hbase_version}}.tar.gz'
            checksum: '{{hbase_checksum}}'
        - name: Make /tmp/Hbase directory
          file:
            path: /tmp/Hbase
            state: directory
            mode: 0755
        - name: Untar Hbase to /tmp/Hbase
          unarchive:
            src: '/tmp/hbase-{{hbase_version}}.tar.gz'
            dest: /tmp/Hbase
            remote_src: true

  post_tasks:
    - name: System Reseal
      script: ../common-packer/provision/system-reseal.sh
      become: true
