---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo

  pre_tasks:
    - include_role: name=lfit.system-update

  tasks:
    - name: 'Install OpenVSwitch {{ovs_version}}'
      block:
        - name: 'Install dependencies required for OpenVSwitch {{ovs_version}}'
          apt: 'name={{item}} state=present'
          with_items:
            - dh-autoreconf
            - debhelper
            - autoconf
            - automake
            - libssl-dev
            - pkg-config
            - bzip2
            - openssl
            - python-all
            - procps
            - python-qt4
            - python-zopeinterface
            - python-twisted-conch
          become: true
        - name: 'Install OpenVSwitch {{ovs_version}}'
          apt: 'name={{item}} state=present'
          with_items:
            - openvswitch-switch
            - openvswitch-vtep
          become: true
        - name: Enable openvswitch-switch service
          systemd:
            name: openvswitch-switch
            enabled: true
            masked: false
          become: true
        - name: Enable openvswitch-vtep service
          systemd:
            name: openvswitch-vtep
            enabled: true
            masked: false
          become: true

    - name: Install Mininet
      apt: name=mininet state=present
      become: true

    - name: 'Install mtcbench'
      block:
        - name: 'Install dependencies required to build mtcbench'
          apt: 'name={{item}} state=present'
          with_items:
            - autoconf
            - automake
            - build-essential
            - libconfig-dev
            - libffi-dev
            - libpcap-dev
            - libssl-dev
            - libssl-doc
            - libsnmp-dev
            - libtool
            - make
            - snmp
            - snmpd
            - pkg-config
          become: true
        - name: Create mtcbench in /tmp
          file:
            path: /tmp/mtcbench
            state: directory
            mode: 0755
        - name: 'Clone mtcbench repository'
          git:
            repo: 'https://github.com/intracom-telecom-sdn/mtcbench.git'
            dest: /tmp/mtcbench
        - name: Provision mtcbench
          command: ./mtcbench/deploy/docker/provision.sh
          args:
            chdir: /tmp
          become: true
        # TODO: remove workaround for build issue with mtcbench
        # when mtcbench dependency build correctly
        # https://github.com/intracom-telecom-sdn/mtcbench/issues/10
        - name: 'Build mtcbench'
          command: ./mtcbench/build_mtcbench.sh || true
          args:
            chdir: /tmp
          ignore_errors: True
        - name: 'Run make mtcbench'
          command: make
          args:
            chdir: /tmp/mtcbench/oflops/cbench
        - name: 'Install cbench to /usr/local/bin'
          copy:
            src: /tmp/mtcbench/oflops/cbench/cbench
            dest: /usr/local/bin
            mode: 0755
            remote_src: true
          become: true

    - name: Install exabgp
      apt: name=exabgp state=present
      become: true

    - name: Install vlan for vlan based tests in VTN suites
      apt: name=vlan state=present
      become: true

    - name: Install python-netaddr for custom mininet topologies
      apt: name=python-netaddr state=present
      become: true

  post_tasks:
    - name: System Reseal
      script: ../common-packer/provision/system-reseal.sh
      become: true
