---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo
  vars:
    ovs_version: 2.6.10
    ovs_checksum: sha256:dc9017013e57e90806a5ee11d5a6b815bc37fab7bec3d713296a16c749c01084

  pre_tasks:
    - include_role: name=lfit.system-update

  tasks:
    - name: "Install OpenVSwitch {{ovs_version}}"
      block:
        - name: "Install dependencies required for OpenVSwitch {{ovs_version}}"
          apt:
            name:
              - dh-autoreconf
              - debhelper
              - autoconf
              - automake
              - libssl-dev
              - pkg-config
              - bzip2
              - openssl
              - python-all
              - procps
              - python-qt4
              - python-zopeinterface
              - python-twisted-conch
            state: present
          become: true
        - name: Create OVS root
          file:
            path: /opt/ovs
            state: directory
            mode: 0755
          become: true
        - name: "Fetch OpenVSwitch {{ovs_version}} to /tmp"
          get_url:
            url: "http://openvswitch.org/releases/openvswitch-{{ovs_version}}.tar.gz"
            dest: "/tmp/openvswitch-{{ovs_version}}.tar.gz"
            checksum: "{{ovs_checksum}}"
        - name: "Unarchive OpenVSwitch {{ovs_version}}"
          unarchive:
            src: "/tmp/openvswitch-{{ovs_version}}.tar.gz"
            dest: /opt/ovs
            remote_src: true
          become: true
        - name: "Build OpenVSwitch {{ovs_version}}"
          shell: DEB_BUILD_OPTIONS='parallel=8 nocheck' fakeroot debian/rules binary
          args:
            chdir: "/opt/ovs/openvswitch-{{ovs_version}}"
          become: true
        - name: "Install OpenVSwitch {{ovs_version}}"
          apt: "deb={{item}}"
          with_items:
            - /opt/ovs/openvswitch-common_2.6.10-1_amd64.deb
            - /opt/ovs/openvswitch-switch_2.6.10-1_amd64.deb
            - /opt/ovs/python-openvswitch_2.6.10-1_all.deb
            - /opt/ovs/openvswitch-vtep_2.6.10-1_amd64.deb
          become: true
        - name: Enable openvswitch-switch service
          systemd:
            name: openvswitch-switch
            enabled: true
            masked: false
          become: true
        - name: Enable openvswitch-vtep service
          systemd:
            name: openvswitch-vtep
            enabled: true
            masked: false
          become: true

    - name: Install Mininet
      apt: name=mininet state=present
      become: true

    - name: Install exabgp
      apt: name=exabgp state=present
      become: true

    - name: Install vlan for vlan based tests in VTN suites
      apt: name=vlan state=present
      become: true

    - name: Install python-netaddr for custom mininet topologies
      apt: name=python-netaddr state=present
      become: true

  post_tasks:
    - name: System Reseal
      script: ../common-packer/provision/system-reseal.sh
      become: true
