---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo

  pre_tasks:
    - include_role: name=lfit.system-update

  tasks:
    - name: Install robot dependencies on CentOS 7
      yum:
        name:
          - postgresql-devel
          - python-docker-py
          - python-matplotlib
          - python-netaddr
          - python36-pip
        state: present
      become: true
      when:
        - ansible_facts['os_family'] == 'RedHat'
        - ansible_facts['distribution_major_version'] is version('8', '<')

    - name: Install robot dependencies on CentOS 8
      yum:
        name:
          - postgresql-devel
          - python3-docker
          - python3-matplotlib
          - python3-netaddr
          - python38-pip
        state: present
      become: true
      when:
        - ansible_facts['os_family'] == 'RedHat'
        - ansible_facts['distribution_major_version'] is version('8', '>=')

    - name: Install lispflowmapping dependencies
      block:
        - name: Install lispflowmapping dependencies
          yum:
            name:
              - boost-devel
              - libpcap-devel
              - libxml2-devel
              - libxslt-devel
            state: present
          become: true

        - name: Install lispflowmapping dependencies for CentOS 7
          yum:
            name:
              - python-docker-py
              - python-netaddr
            state: present
          become: true
          when:
            - ansible_facts['distribution_major_version'] is version('8', '<')

        - name: Install lispflowmapping dependencies for CentOS 8
          yum:
            name:
              - python3-docker
              - python3-netaddr
            state: present
          become: true
          when:
            - ansible_facts['distribution_major_version'] is version('8', '>=')

        - name: Install udpreplay
          block:
            - name: Fetch udpreplay git repo
              git:
                repo: https://github.com/ska-sa/udpreplay.git
                dest: /tmp/udpreplay
            - name: Run bootstrap.sh script
              command: /tmp/udpreplay/bootstrap.sh
              args:
                chdir: /tmp/udpreplay
            - name: Run configure script
              command: /tmp/udpreplay/configure
              args:
                chdir: /tmp/udpreplay
            - name: Run make
              command: make
              args:
                chdir: /tmp/udpreplay
            - name: Install udpreplay to /usr/local/bin/udpreplay
              copy:
                src: /tmp/udpreplay/udpreplay
                dest: /usr/local/bin/udpreplay
                mode: 0755
                owner: root
                remote_src: true
              become: true
      when:
        - ansible_facts['os_family'] == 'RedHat'

  post_tasks:
    - name: System Reseal
      script: ../common-packer/provision/system-reseal.sh
      become: true
