#!/bin/bash
until host github.com &>/dev/null
do
    echo "Waiting until github.com is resolvable..."
done
git clone --recursive https://github.com/opendaylight/releng-builder.git /opt/ciman
/opt/ciman/global-jjb/jenkins-init-scripts/init.sh


